FROM docker.io/briar/ci-image-android:latest

# Install fdroidserver and other tools
RUN apt update && apt-get -qy install --no-install-recommends \
    pipx \
    python3-pip \
    python3-wheel \
    python3-setuptools \
    openssh-client \
    rsync

ENV PATH="${PATH}:/root/.local/bin"
RUN pipx install git+https://gitlab.com/fdroid/fdroidserver.git

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64

# Deployment to F-droid nightly
ENV FDROID_REPO_KEY        /inputs/fdroid-repo-key.txt
ENV NIGHTLY_KEYSTORE_PATH  /inputs/taler-nightly.keystore
ENV NIGHTLY_KEYSTORE_ALIAS androiddebugkey
ENV NIGHTLY_KEYSTORE_PASS  android

# Deployment to taler.net/files
ENV SCP_SSH_KEY  /inputs/wallet.taler.net
ENV SCP_SSH_HOST files@gnunet.org
ENV SCP_SSH_PATH ~

RUN echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"
RUN ln -s $ANDROID_HOME/build-tools/35.0.0/apksigner /usr/bin/

WORKDIR /workdir
